### ISSUE TITLE
建议最终抽中的礼物可以配置

### ISSUE THREAD

**Issue by anywayuan** [KKKyrie/giftie#1]
最中抽中的礼物要是可以配置就好了。  就是我配置了，不论怎么抽都是这个礼物，不配置的话就随机抽。

**Comment by KKKyrie** [comment]
下个版本会支持 :rocket:

**Comment by anywayuan** [comment]
已start关注   期待！
________________________________
发件人: kyrieliu <notifications@github.com>
发送时间: 2021年2月26日 14:25
收件人: KKKyrie/giftie <giftie@noreply.github.com>
抄送: YAKI <yoankisstt@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [KKKyrie/giftie] 建议最终抽中的礼物可以配置 (#1)


下个版本会支持 🚀

**Comment by KKKyrie** [comment]
「礼物可配置」已支持，详情参见 `gift.setting.js` 的 `targetGiftIndex` 字段
