### ISSUE TITLE
Build 后的文件 指的是 public 文件夹吧？

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [KKKyrie/giftie#13]
没学过前端，readme 里

Build 后的文件 指的是 public 文件夹吧？

**Comment by sanbeichahegongheguo** [comment]
好像就是 指 build 之后 单独的文件。

**Comment by KKKyrie** [comment]
> 好像就是 指 build 之后 单独的文件。

`public` 是静态资源存放的地方。  
build 之后的东西在 `/dist` 里面。  
有个辨认小技巧，build 命令执行后多出来的那个文件夹就是。
