### ISSUE TITLE
生成静态之后改完url上传了访问会出现一直loading，而不是和npm run serve的时候的样子

### ISSUE THREAD

**Issue by everyonelovesCCP** [KKKyrie/giftie#26]
![image](https://user-images.githubusercontent.com/71995715/217644100-4ba18804-a1cf-4dc2-a4c7-172e23819141.png)
https://52wjj.njyns.com/choujiang/index.html
![image](https://user-images.githubusercontent.com/71995715/217644550-08cc3836-51bb-4a30-882b-b433e2457ad8.png)

**Comment by everyonelovesCCP** [comment]
发现问题了，只能在主目录，不能在子目录

**Comment by bainningking** [comment]
> 

我npm run build之后，把dist目录下的文件部署到gh-pages分支，github pages打开也是Loading，大佬咋解决的啊，新手求教
