### ISSUE TITLE
npm run build 编译报错，好像是依赖问题，用的是v16.19.0，非前端排查好累，求版本依赖说明

### ISSUE THREAD

**Issue by CoffinLove** [KKKyrie/giftie#36]
TypeError: transpileDependencies.map is not a function

**Comment by CoffinLove** [comment]
为了解决这个问题，我将 的版本更改@vue/cli-plugin-babel为"~5.0.0".

**Comment by yang3121099** [comment]
> 为了解决这个问题，我将 的版本更改@vue/cli-plugin-babel为"~5.0.0".

你好 我也遇到了同样的问题，请问你修改这个参数是package.json一处吗，我看yarn.lock也有这个，但是不知道啥意思，修改完运行npm run serve还是报错 : (

**Comment by KKKyrie** [comment]
@CoffinLove @yang3121099 
这些是由于 github 检测依赖的安全漏洞后，自动升级版本导致的问题

请尝试恢复以下依赖的版本：
本地 node 版本：14.15.0
@vue/cli-service 版本：4.5.0
重新 pull 下 main 分支（新增了 eslint 配置，因为 eslint 版本也有问题）
需要重新安装依赖后再 `run serve`

**Comment by KKKyrie** [comment]
> @CoffinLove @yang3121099 这些是由于 github 自动检测依赖的安全漏洞后，自动升级依赖版本导致的问题
> 
> 请尝试恢复以下依赖的版本： 本地 node 版本：14.15.0 @vue/cli-service 版本：4.5.0 重新 pull 下 main 分支（新增了 eslint 配置，因为 eslint 版本也有问题） 需要重新安装依赖后再 `run serve`

晚点我会将新的配置重新上传到仓库（测试通过后会关闭本条 issue），在这之前先自行本地修改哈

**Comment by KKKyrie** [comment]
请查看最新的 README

**Comment by klxs660** [comment]
> TypeError: transpileDependencies.map is not a function
修改 vue.config.js，添加配置项 transpileDependencies: [] ，就可以了
