### ISSUE TITLE
构建时会有警告模块解析错误

### ISSUE THREAD

**Issue by uuau99999** [KKKyrie/giftie#42]
构建serve/build会出现以下警告：
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/6498327/218682646-e4b892e5-8f03-4c27-9e28-3ce291b3612c.png">
public下每个文件都会提示文件解析报错。看了下原因应该是这里的动态引入:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/6498327/218682904-aa8173a8-514c-4443-92a8-703f92097fc2.png">
这里的动态引入会让webpack把public下所有可能的文件bundle进最终的产物，但由于缺少对应loader会报错。
这里建议作者改变这里的图片动态引入的方式，不要在require中使用动态字符，public下内容应该不需要做处理且应该在根路径下可以访问，直接用相对路径:
```js
let data = gifts.map(item => {
  return {
    fullName: item.name,
    name: item.alias,
    img: `/public${item.image}`,
    top: '70%',
  };
});
```

**Comment by KKKyrie** [comment]
感谢，一个很有价值的小细节。  
fixed, 详情查看：[https://github.com/KKKyrie/giftie/pull/43](https://github.com/KKKyrie/giftie/pull/43/files#diff-96371f4e1111b5850727c58eb2b1dbd4e707b5685d0e0f4a92443fce67873f1c)
